name: gene_annot
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bcrypt=3.2.0
  - blas=2.106
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - docutils=0.16
  - dropbox=11.4.1
  - filechunkio=1.8
  - ftputil=5.0.1
  - idna=2.10
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.12
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - llvm-openmp=11.1.0
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1k
  - pandas=1.1.3
  - paramiko=2.7.2
  - pip=21.0.1
  - ply=3.11
  - psutil=5.8.0
  - pycparser=2.20
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.0
  - requests=2.25.1
  - setuptools=49.6.0
  - six=1.15.0
  - snakemake=3.13.3
  - sqlite=3.35.3
  - stone=3.2.1
  - tk=8.6.10
  - urllib3=1.26.4
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
